# 公共配置
common:
  debug: false
  autoTable: true #自动初始化表结构
  logDir: logs #日志目录

# jwt配置
jwt:
  expired: 3600 # 单位秒
  secret: v#z2QeXHYw#%C0VLnl
  issuer: watt_jwt_issuer
  header: Authorization

# 跨域设置
cross:
  domain: "*"
  header: "*"
  method: "POST, OPTIONS, GET, PUT"

# http服务参数
http:
  port: 80
  readTimeout:  60
  writeTimeout:  60

# 数据库服务
database:
  
  mysql:
    type: mysql 
    host: host.docker.internal
    #host: localhost
    user: root
    password: 123456
    #password: root
    port: 3306
    dbname: watt
    charset: utf8
    timeout: 10
    prefix: watt_
  redis:    
    host: localhost
    password: ""
    port: 6379
    database: 0
    timeout: 5
